project:
  type: website

website:
  title: "OSCT.Software.stewards.at.UT.31.10.2024.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



